### ISSUE TITLE
DB:SEED doesn't Seed

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#87] opened 2018-09-13 13:40 UTC
Fix this task. Include a few test fixtures for a dev database. What's there now was the actual content from the database migration of the old system.

**Comment by kevinreiss** [comment] 2018-09-13 18:12
https://github.com/pulibrary/DSS/issues/87

**Comment by sandbergja** [comment] 2022-04-20 22:54
closing, since it is a duplicate of #237

**Closed by sandbergja** 2022-04-20 22:54 UTC
